#!/bin/sh
#
# Runs the default Grunt tasks before committing
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Redirect output to stderr.
exec 1>&2

exec grunt

