call npm uninstall @esri/arcgis-rest-auth
call npm uninstall @esri/arcgis-rest-common-types
call npm uninstall @esri/arcgis-rest-feature-service-admin
call npm uninstall @esri/arcgis-rest-groups
call npm uninstall @esri/arcgis-rest-items
call npm uninstall @esri/arcgis-rest-request
call npm uninstall @esri/arcgis-rest-sharing
call npm install @esri/arcgis-rest-request
call npm install @esri/arcgis-rest-auth
call npm install @esri/arcgis-rest-portal
call npm install @esri/arcgis-rest-feature-layer
call npm install @esri/arcgis-rest-service-admin
call npm install @esri/arcgis-rest-geocoding
call npm install @esri/arcgis-rest-routing
call npm install @esri/arcgis-rest-types
